### ISSUE TITLE
[Bug]: DemoDebug Local test failed

### ISSUE THREAD

**Issue by Jaehwa-Noh** [android/nowinandroid#1242] opened 2024-03-04 04:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

Run local tests on DemoDebug variant: ./gradlew testDemoDebug
has failed test on the barely fork the repository.

I entered the command in the  Execute Gradle Task on android studio.
<img width="491" alt="image" src="https://github.com/android/nowinandroid/assets/48680511/f393365e-33da-4011-b3ac-55e870603d8e">

But the test does not success, see below.
<img width="362" alt="image" src="https://github.com/android/nowinandroid/assets/48680511/bd771458-d384-441c-a7c9-060299f102ab">

Any thing I missed? or is this already known issue?

### Relevant logcat output

```shell
Output is so long, I'd add partially.

java.lang.IllegalArgumentException: resource native/windows/x86_64/robolectric-nativeruntime.dll not found.

java.io.IOException: Unable to rename C:\Users\Jaehwa\AppData\Local\Temp\junit4146744981157378858\user_preferences_test.pb.tmp.This likely means that there are multiple instances of DataStore for this file. Ensure that you are only creating a single instance of datastore for this file.

14 tests completed, 4 failed
14 tests completed, 4 failed


        Caused by: java.io.IOException at NiaPreferencesDataSourceTest.kt:92

        Caused by: java.io.IOException at NiaPreferencesDataSourceTest.kt:74

        Caused by: java.io.IOException at NiaPreferencesDataSourceTest.kt:53

        Caused by: java.io.IOException at NiaPreferencesDataSourceTest.kt:92

        Caused by: java.io.IOException at NiaPreferencesDataSourceTest.kt:74

        Caused by: java.io.IOException at NiaPreferencesDataSourceTest.kt:53
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sanao1006** [comment] 2024-03-04 05:32
Are You a Windows OS User?
Now in Android screenshot test library uses Roborazzi. This library uses Robolectric NATIVE GraphicsMode internally, but this does not support Windows OS and seems to cause the following error
```
java.lang.IllegalArgumentException: resource native/windows/x86_64/robolectric-nativeruntime.dll not found.
```
So, the local screenshot tests would fail on Windows OS.
ref: https://github.com/robolectric/robolectric/issues/8312

  
I am not sure of the exact cause of the problem with the DataStore, but I have encountered the same error, too.

**Comment by Jaehwa-Noh** [comment] 2024-03-04 05:39
Thank you, I didn't know Roborazzi doesn't support Windows OS.
You say, encountered same error with DataStore, it gives me relief.

**Comment by sanao1006** [comment] 2024-03-04 05:52
> Roborazzi doesn't support Windows OS.

I think it would be correct to express that Roborazzi does not support the Windows OS, but rather Robolectric NATIVE GraphicsMode does not support the Windows OS!

**Comment by Jaehwa-Noh** [comment] 2024-03-04 05:53
Yes, I agree with that.
> So, the local screenshot tests would fail on Windows OS.
> ref: https://github.com/robolectric/robolectric/issues/8312
I check that word from yours link.

**Comment by SimonMarquis** [comment] 2024-03-04 09:55
The issue with Roborazzi and DataStore are two different issue.
For the DataStore issue, you can read more on this issue (especially the last comment with links):
- https://github.com/android/nowinandroid/issues/98#issuecomment-1320886904

**Comment by SimonMarquis** [comment] 2024-03-30 06:04
> Robolectric 4.11 adds support for the native runtime (native SQLite and graphics modes) on Windows.
https://github.com/robolectric/robolectric/releases/tag/robolectric-4.12

**Comment by JackEblan** [comment] 2024-03-30 06:07
> > Robolectric 4.11 adds support for the native runtime (native SQLite and graphics modes) on Windows.
> > https://github.com/robolectric/robolectric/releases/tag/robolectric-4.12

Wow finally😲♥️

**Comment by JackEblan** [comment] 2024-03-30 09:51
@SimonMarquis I recently tried to use Roborazzi in my app but it get stucked 😅 when I ran it on my machine. Maybe Roborazzi needs to update too or I'm the only one experiencing this.

**- Windows 10**
**- Iguana**

**Comment by SimonMarquis** [comment] 2024-03-30 18:59
Unfortunately there still seems to be issues with windows runners...

**Comment by takahirom** [comment] 2024-03-31 08:58
I was unable to reproduce this issue in [roborazzi repository](https://github.com/takahirom/roborazzi/pull/287). 
Therefore, I attempted to use the nowinandroid repository and tried fixing it with ActivityScenario.close, but [it seems to be ineffective](https://github.com/takahirom/nowinandroid/pull/2/files).
I also reviewed the Robolectric repository and noticed that @hoisie addressed a similar issue last week.
https://github.com/robolectric/robolectric/commit/3b90118de04963282bc2389544ccfdc194dd1945#diff-31315cbee32dff759fd6d17e6d8939e67a292dc9e6c05591e4b95462a5ef1c43R44

@hoisie
It might seem a bit abrupt, but are you aware of this?

**Comment by hoisie** [comment] 2024-03-31 15:56
> > Robolectric 4.11 adds support for the native runtime (native SQLite and graphics modes) on Windows.
> > https://github.com/robolectric/robolectric/releases/tag/robolectric-4.12

Just to be clear, this was a typo, and should read 4.12 release.

Windows seems to be a lot more protective of files that have been opened in native code. For instance, unlike in Mac and Linux, it's not possible to delete the temp native runtime DLL file in the same process where it was opened. We are seeing something similar with font files too. This is why we have extra cleanup logic for Windows.

**Comment by hoisie** [comment] 2024-03-31 16:11
I am not sure that the `FileSystemException` errors you are seeing are causing test failures:

```
ERROR: Failed to destroy temp directory

java.nio.file.FileSystemException: C:\Users\RUNNER~1\AppData\Local\Temp\robolectric-nativeruntime12669726669700075741\fonts\CarroisGothicSC-Regular.ttf: The process cannot access the file because it is being used by another process
```

This deletion logic occurs in a shutdown hook, so it would run after all tests are complete. I think we should completely remove these error messages on Windows, because they will cause a lot of noise and confusion. 

I think that the tests are failing due to other reasons.

**Comment by SimonMarquis** [comment] 2024-03-31 17:51
You are probably right. I can't test it further since I don't have my Windows machine with me, but the errors seem to come from other IO Exceptions.

```
com.google.samples.apps.nowinandroid.ui.NiaAppScreenSizesScreenshotTests > expandedWidth_compactHeight_showsNavigationRail FAILED
    java.io.IOException at SingleProcessDataStore.kt:433
        Caused by: java.io.IOException at NiaAppScreenSizesScreenshotTests.kt:126
```

**Comment by SimonMarquis** [comment] 2024-04-01 11:52
Renders with Windows runners are different for the NavigationBar / NavigationRail tests:

|Screenshots |
|--------|
| ![compactWidth_compactHeight_showsNavigationBar_compare](https://github.com/android/nowinandroid/assets/1921278/0bf397ab-5f41-4709-a1bb-aede53be0d6f) |
| ![compactWidth_expandedHeight_showsNavigationBar_compare](https://github.com/android/nowinandroid/assets/1921278/3b3a929e-e0f1-4a57-985c-70f4b577c423) |
| ![compactWidth_mediumHeight_showsNavigationBar_compare](https://github.com/android/nowinandroid/assets/1921278/dc86464d-b300-4102-9c88-85506b61979e) |
| ![expandedWidth_compactHeight_showsNavigationRail_compare](https://github.com/android/nowinandroid/assets/1921278/88d8e377-ed9a-47cb-8865-ccd8475735e0) | 

https://github.com/SimonMarquis/nowinandroid/actions/runs/8507483157?pr=24#artifacts

**Comment by hoisie** [comment] 2024-04-02 19:37
https://github.com/robolectric/robolectric/releases/tag/robolectric-4.12.1 was just released which should reduce the amount of log noise in Windows (though it won't fix the underlying cause of this issue).

RE comparing screenshots across platforms (i.e. Linux / Mac / Linux):
There are no guarantees that rendering will be consistent across different platforms. The underlying native libraries (e.g. skia, minikin, etc..) have platform-specific implementation details.

**Comment by SimonMarquis** [comment] 2024-04-02 22:25
Could this be an issue related to Looper/Dispatcher that would not behave exactly the same?
I feel like the screenshots are not rendering the expected "state".

There are some state setup in `@Before` that does not seem to be applied on Windows (hence the screenshot differences)

https://github.com/android/nowinandroid/blob/88c3eb0b90ace5499962d9495464fa2388ec9e9a/app/src/testDemo/kotlin/com/google/samples/apps/nowinandroid/ui/NiaAppScreenSizesScreenshotTests.kt#L125-132

**Comment by SimonMarquis** [comment] 2024-07-11 21:28
@Jaehwa-Noh a fix has been implemented in #1542 for your initial bug report, can you check if the fix works for you as well?

**Comment by SimonMarquis** [comment] 2024-07-11 21:30
This might also fix the secondary issue, let us know.

**Comment by Jaehwa-Noh** [comment] 2024-07-12 04:20
Okay I'll test it as soon as possible.

**Comment by Jaehwa-Noh** [comment] 2024-07-12 11:02
@SimonMarquis 
https://github.com/android/nowinandroid/pull/1542#pullrequestreview-2174456503
It works.

**Comment by SimonMarquis** [comment] 2024-10-14 18:19
@Jaehwa-Noh do you still reproduce this issue?
It should have been fixed with:
- #1542

If that is the case, you can close the issue.
Thanks 🙏

**Comment by Jaehwa-Noh** [comment] 2024-10-14 21:53
https://github.com/android/nowinandroid/pull/1542#pullrequestreview-2174456503

Done. Thank you.

**Closed** 2024-10-14 21:53 UTC
Labels: bug
