### ISSUE TITLE
[Bug]: The unit test offlineFirstTopicsRepository_toggle_followed_topics_logic_delegates_to_nia_preferences() failed

### ISSUE THREAD

**Issue by Bwaim** [android/nowinandroid#98] opened 2022-06-02 19:26 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?
**Windows environment**
Running the unit test offlineFirstTopicsRepository_toggle_followed_topics_logic_delegates_to_nia_preferences() fails.
There is an exception thrown that is cached but the log of this exception causes crash because it's not mocked, the original exception is :

`java.io.IOException: Unable to rename C:\xxxxx\Temp\junit2206256684596171052\user_preferences_test.pb.tmp.This likely means that there are multiple instances of DataStore for this file. Ensure that you are only creating a single instance of datastore for this file.`

The stacktrace :

```
androidx.datastore.core.SingleProcessDataStore.writeData$datastore_core(SingleProcessDataStore.kt:433)
androidx.datastore.core.SingleProcessDataStore.transformAndWrite(SingleProcessDataStore.kt:410)
androidx.datastore.core.SingleProcessDataStore.access$transformAndWrite(SingleProcessDataStore.kt:76)
androidx.datastore.core.SingleProcessDataStore$transformAndWrite$1.invokeSuspend(SingleProcessDataStore.kt)
\b\b\b(Coroutine boundary.\b(\b)
com.google.samples.apps.nowinandroid.core.datastore.NiaPreferences.toggleFollowedTopicId(NiaPreferences.kt:46)
com.google.samples.apps.nowinandroid.core.data.repository.OfflineFirstTopicsRepositoryTest$offlineFirstTopicsRepository_toggle_followed_topics_logic_delegates_to_nia_preferences$1.invokeSuspend(OfflineFirstTopicsRepositoryTest.kt:190)
```

I think the problem is because the test was executed under a Windows environment and the rename failed on that platform (`SingleProcessDataStore.kt : 432`) :

```
            if (!scratchFile.renameTo(file)) {
                throw IOException(
                    "Unable to rename $scratchFile." +
                        "This likely means that there are multiple instances of DataStore " +
                        "for this file. Ensure that you are only creating a single instance of " +
                        "datastore for this file."
                )
            }
```

### Relevant logcat output

```shell
Method e in android.util.Log not mocked. See http://g.co/androidstudio/not-mocked for details.
java.lang.RuntimeException: Method e in android.util.Log not mocked. See http://g.co/androidstudio/not-mocked for details.
	at android.util.Log.e(Log.java)
	at com.google.samples.apps.nowinandroid.core.datastore.NiaPreferences.toggleFollowedTopicId(NiaPreferences.kt:59)
	at com.google.samples.apps.nowinandroid.core.datastore.NiaPreferences$toggleFollowedTopicId$1.invokeSuspend(NiaPreferences.kt)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Rocksnake** [comment] 2022-06-03 16:51
I think the reason should be that two DataStore's writing at the same time, one of the renames seems to be failing, because the file no longer exists.

I think the place where the problem occurs should be in the `TestDataStoreModule.kt` file, We should instead create the DataStore once, then inject the instance where necessary or manage it as a singleton.
![image](https://user-images.githubusercontent.com/44219737/171909958-138636b0-e364-4e23-949a-2df81cf1f48f.png)

**Comment by alexvanyo** [comment] 2022-09-01 16:28
Hi, is this still an issue with the latest version?

**Comment by SimonMarquis** [comment] 2022-11-18 23:47
FWIW, on a Windows machine, I'm unable to run the whole test suite. It always fails with file locks and/or `android.util.Log` not beeing mocked.

**Comment by SimonMarquis** [comment] 2022-11-19 13:33
It seems to be a known issue on Windows:
- https://issuetracker.google.com/issues/194301881
- https://issuetracker.google.com/issues/194208090
- https://issuetracker.google.com/issues/203087070
- https://github.com/googlecodelabs/android-datastore/issues/48

**Comment by SimonMarquis** [comment] 2024-03-06 21:51
`androidx.datastore:datastore-*:1.1.0-beta02` landed:

> Fixed the issue where file rename fails during updateData in non-Android JVM environments. ([b/203087070](https://b.corp.google.com/issues/203087070))
> https://developer.android.com/jetpack/androidx/releases/datastore#1.1.0-beta02

Unfortunately, the issue persists...

**Comment by JackEblan** [comment] 2024-03-08 14:47
Hello @SimonMarquis I am also experiencing this `java.io.IOException: Unable to rename C:\Users\User\AppData\Local\Temp\junit481202955115791832\user_preferences_test.pb.tmp.This likely means that there are multiple instances of DataStore for this file. Ensure that you are only creating a single instance of datastore for this file.` Is there a way to make this work on my Windows 10?

**Comment by SimonMarquis** [comment] 2024-03-08 14:51
No, but you can ⭐ & +1 this issue: https://issuetracker.google.com/issues/203087070

**Comment by SimonMarquis** [comment] 2024-07-11 21:28
@Bwaim a fix has been implemented in #1542, can you check if the fix works for you as well?

**Comment by Bwaim** [comment] 2024-07-11 22:22
@SimonMarquis unfortunately I can't check as I don't have a Windows anymore 😞

**Comment by SimonMarquis** [comment] 2024-10-14 18:18
@Bwaim do you still reproduce this issue?
It should have been fixed with:
- #1542

If that is the case, you can close the issue.
Thanks 🙏

**Closed** 2024-10-14 18:34 UTC
Labels: bug, waiting
