### ISSUE TITLE
[Bug]: Gradle Managed Devices workflow is succeeding, while not actually successfully running the tests

### ISSUE THREAD

**Issue by alexvanyo** [android/nowinandroid#532] opened 2023-01-13 00:15 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

For example: This run failed with licenses not being accepted, but the overall workflow still passed:
https://github.com/android/nowinandroid/actions/runs/3907037956/jobs/6675824472

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by doasmike** [comment] 2023-01-17 01:02
Actually, you can't classify this as an bug because the next step in this workflow - uploading test results - has a setting of `if: success() || failure()`.
So the workflow executed correctly as intended :)

**Comment by thagikura** [comment] 2023-01-20 03:40
Fixed by #537

**Closed by thagikura** 2023-01-20 03:40 UTC
Labels: bug
