### ISSUE TITLE
[Bug]: "Try another search..." text is not visible in dark mode

### ISSUE THREAD

**Issue by RivanParmar** [android/nowinandroid#894] opened 2023-08-12 19:14 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

The `ClickableText` containing the `tryAnotherSearchString` in the `EmptySearchResultBody` composable is not visible in dark mode.

| | Light mode | Dark mode|
| --- | --- | --- |
| Default Theme | ![Screenshot_20230813-004714.png](https://github.com/android/nowinandroid/assets/77159650/6308cb5c-099a-4cfb-b0a4-50e78bdf0b64) | ![Screenshot_20230813-004706.png](https://github.com/android/nowinandroid/assets/77159650/815e4d42-bce0-4b49-9a01-8ea54b29e59f) |
| Android Theme | ![Screenshot_20230813-004637.png](https://github.com/android/nowinandroid/assets/77159650/f79d87be-655f-446e-ba8f-6aca5d545842) | ![Screenshot_20230813-004653.png](https://github.com/android/nowinandroid/assets/77159650/7fd587aa-43f5-4c5b-b61d-7674cd782310) |

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SimonMarquis** [comment] 2023-08-14 08:09
I think this is a duplicate of

- #837

**Comment by RivanParmar** [comment] 2023-08-14 08:49
Sorry, didn't see that issue was already there as the title was different. Am closing this issue.

**Closed** 2023-08-14 08:51 UTC
Labels: bug
