### ISSUE TITLE
[Bug]:  Theme does not change navigation bar

### ISSUE THREAD

**Issue by cleissondarosa** [android/nowinandroid#657] opened 2023-04-13 12:12 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

When I click on settings to change app theme, navigation bar doesn't change instantly causing navigation bar conflict.

I'm using a Galaxy S10+

https://user-images.githubusercontent.com/98971466/231753333-52e49de7-f869-4227-84dc-fa61c1a99d67.mp4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alexvanyo** [comment] 2023-04-14 15:15
Which version of the app are you seeing this on? Is the the version downloaded from the Play Store, or built from source?

This looks like a duplicate of #422 which should be fixed locally, but not in the Play Store version yet.

**Comment by cleissondarosa** [comment] 2023-04-14 16:33
I downloaded it from the play store this week.

**Comment by alexvanyo** [comment] 2023-04-14 19:32
Thank you! This should be fixed then when we make our next release on the Play Store.

**Closed by alexvanyo** 2023-04-14 19:32 UTC
Labels: bug
