### ISSUE TITLE
[FR]: Multigraph Navigation

### ISSUE THREAD

**Issue by fi8er1** [android/nowinandroid#885] opened 2023-08-09 07:37 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

Most, if not all, apps require at least a separate auth (signin, signup) graph from the main.

### Describe the solution

Provide a proper example of handling multigraph navigation.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fi8er1** [comment] 2023-08-09 23:54
I'm currently migrating my app to use Jetpack Compose and need to know the basic logic for my issue that I created?

Do we need to maintain a single Root Graph and switch between the screen based on the UserAuthenticationState? Or should we create separate root graphs for the "Auth" and "Home" ? @tunjid

**Comment by tunjid** [comment] 2023-08-10 00:06
@fi8er1 You want to use a nested navigation graph for this as covered in the [documentation](https://developer.android.com/jetpack/compose/navigation#nested-nav).

When signed in, you navigate to your "home" nav graph, when signed out you navigate to the "auth" nav graph. Your root nav graph hosts these two nested nav graphs.

**Comment by fi8er1** [comment] 2023-08-10 08:27
@tunjid 
Ok, do we keep the bottomBar in "Main" and hide show it based on the authentication state... or move it to the "Home"?

**Comment by tunjid** [comment] 2023-08-11 19:30
@fi8er1  That would depend on the requirements of your app. I think keeping the bottomBar in the root nav graph and animating it away as the navigation state changes would be nice, but its your call.

**Comment by fi8er1** [comment] 2023-08-11 19:36
I don't see any possible way of navigating back to the Auth navHost upon logout. Do I need to keep the Auth and Home screens in the single NavHost? This is quite confusing.

**Comment by tunjid** [comment] 2023-08-11 19:43
@fi8er1 You can have nested navigation graphs. In your NavHost you can define "home" and "auth" as nested nav graphs in a single nav host. In NiA for example, we have the [interests nav graph](https://github.com/android/nowinandroid/blob/main/app/src/main/java/com/google/samples/apps/nowinandroid/navigation/NiaNavHost.kt#L63) is a nested nav graph.

[This](https://github.com/android/nowinandroid/blob/main/feature/interests/src/main/java/com/google/samples/apps/nowinandroid/feature/interests/navigation/InterestsNavigation.kt#L33) is how navigation a nested nav graph is performed.

**Comment by tunjid** [comment] 2023-08-11 19:45
I'm going to close the issue as NiA already has an example of multigraph navigation, although the scope is not an auth/unauth scope. The same principles apply however.

**Comment by tunjid** [comment] 2023-08-18 21:33
Duplicate of #261

**Closed** 2023-08-18 21:33 UTC
Labels: enhancement

**Comment by fi8er1** [comment] 2023-08-19 14:53
For now I will be putting a pin on migrating to Compose.
Could you be kind and suggest (if there is) a similar sample project with Views?

Thanks
