### ISSUE TITLE
[Refactor] Implement versions catalog classes into the conventions submodule.

### ISSUE THREAD

**Issue by nymexe** [android/nowinandroid#1023] opened 2023-11-07 14:58 UTC
You are using `libs.findLibrary("someLib").get()` in some convention plugin classes to implement the dependencies. Wouldn't it be better if this was `libs.someLib` like in the library/module build.gradle files?

I guess we can obtain this capability by including version catalog-related classes in the `conventions` module like this:

```kotlin
// VersionCatalog classes.
implementation(files(libs.javaClass.superclass.protectionDomain.codeSource.location))
```

By adding these files, we can get rid of the noise that the `.findLibrary().get()` function is adding. Also, we get type-safe dependency providers like this example below:

```kotlin
dependencies {
  add("testImplementation", libs.findLibrary("robolectric").get())
  add("testImplementation", libs.findLibrary("roborazzi").get())

  // Type-safe, and much less noise in code.
  val libs = the<LibrariesForLibs>()
  add("testImplementation", libs.robolectric)
  add("testImplementation", libs.roborazzi)
}
```

I've seen this practice in [Signal-Android](https://github.com/signalapp/Signal-Android/blob/main/build-logic/plugins/build.gradle.kts) repository.

**Comment by SimonMarquis** [comment] 2023-11-08 20:39
👋 Hi @nymexe, this looks like a duplicate of:

- #317
- #318
- #937

**Closed** 2023-11-08 20:47 UTC
